log_wandb: false
seed: 42

filepaths:
  cv_results_dir: "data/cv_results/"
  eval_results_dir: "data/eval_results/"
  eval_plots_dir: "data/eval_plots/"

input_columns:
  date:    "dateID"
  dp_index:    "bdID"
  sku_index:   "skuID"
  target:  "target"
  frequency: "frequency"

datasets:
  - PHARMACY

forecast_columns:
  date:    "date"
  sku_index:   "skuID"
  product_index: "productID"
  store_index: "storeID"
  target:  "demand"
  cutoff: "cutoff"

preprocessing:
  target_transform: "LOCAL_MAX" # Options: "LOCAL_MAX", "LOCAL_STANDARD", "LOCAL_ROBUST"

forecast:
  models:
    - TIDE
  model_config:
    ML:
      num_samples: 1
    FM:
      TOTO:
        num_samples: 50
        samples_per_batch: 25  # Must divide num_samples evenly
      TABPFN:
        n_estimators: 4        # TabPFN ensemble size (internal sampling)
        max_samples: 500       # Max training samples (due to TabPFN limitations)  
        scaling: true          # Apply feature scaling
    NEURAL:
      MIXTURE:
        TGMM:
          num_components: 10
          horizon_correlation: true


cross_validation:
  M5:
    test:
      n_windows: 322
      step_size: 1
      refit: false
    val:
      n_windows: 100
      step_size: 1
      refit: false
  FAVORITA:
    test:
      n_windows: 322
      step_size: 1
      refit: false
    val:
      n_windows: 100
      step_size: 1
      refit: false
  ROHLIK:
    test:
      n_windows: 280   # 20% of 1402 days
      step_size: 1
      refit: false
    val:
      n_windows: 140   # 10% of 1402 days
      step_size: 1
      refit: false
  ROSSMANN:
    test:
      n_windows: 188   # 20% of 942 days
      step_size: 1
      refit: false
    val:
      n_windows: 94    # 10% of 942 days
      step_size: 1
      refit: false
  BAKERY:
    test:
      n_windows: 243   # 20% of 1215 days
      step_size: 1
      refit: false
    val:
      n_windows: 121   # 10% of 1215 days
      step_size: 1
      refit: false
  YAZ:
    test:
      n_windows: 153   # 20% of 765 days
      step_size: 1
      refit: false
    val:
      n_windows: 76    # 10% of 765 days
      step_size: 1
      refit: false
  PHARMACY:
    test:
      n_windows: 24   # 20% of 827 days
      step_size: 1
      refit: false
    val:
      n_windows: 12    # 10% of 827 days
      step_size: 1
      refit: false
  HOTEL:
    test:
      n_windows: 645   # 20% of 3227 days
      step_size: 1
      refit: false
    val:
      n_windows: 322   # 10% of 3227 days
      step_size: 1
      refit: false
  ONLINERETAIL:
    test:
      n_windows: 147   # 20% of 739 days
      step_size: 1
      refit: false
    val:
      n_windows: 73    # 10% of 739 days
      step_size: 1
      refit: false

metrics:
  metrics:
    - MSSE
    - MASE
  seasonality: null # Set to None for allowing seasonality to be detected automatically based on frequency of the dataset
