log_wandb: false
seed: 42

filepaths:
  eval_results_dir: "data/eval_results/"
  eval_plots_dir: "data/eval_plots/"

input_columns:
  date:    "dateID"
  dp_index:    "bdID"
  sku_index:   "skuID"
  target:  "target"
  frequency: "frequency"

datasets:
  - HOTEL

forecast_columns:
  date:    "date"
  sku_index:   "skuID"
  target:  "demand"
  cutoff: "cutoff"

preprocessing:
  target_transform: "LOCAL_MAX" # Options: "LOCAL_MAX", "LOCAL_STANDARD", "LOCAL_ROBUST"

forecast:
  models:
    - ETS
    - LGBM

  horizon: 
    M5: 7
    FAVORITA: 7
    ROHLIK: 7
    ROSSMANN: 7
    BAKERY: 7
    YAZ: 7
    PHARMACY: 4
    HOTEL: 7
    ONLINERETAIL: 7

  lags: 
    M5: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    FAVORITA: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    ROHLIK: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    ROSSMANN: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    BAKERY: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    YAZ: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    PHARMACY: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    HOTEL: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    ONLINERETAIL: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    
  model_config:
    ML:
      num_samples: 1
    FM:
      TOTO:
        num_samples: 50
        samples_per_batch: 25  # Must divide num_samples evenly
      TABPFN:
        n_estimators: 4        # TabPFN ensemble size (internal sampling)
        max_samples: 500       # Max training samples (due to TabPFN limitations)  
        n_lags: 8              # Number of lag features
        scaling: true          # Apply feature scaling

cross_validation:
  M5:
    test:
      cv_windows: 322
      step_size: 1
      refit: false
    val:
      cv_windows: 100
      step_size: 1
      refit: false
  FAVORITA:
    test:
      cv_windows: 322
      step_size: 1
      refit: false
    val:
      cv_windows: 100
      step_size: 1
      refit: false
  ROHLIK:
    test:
      cv_windows: 280   # 20% of 1402 days
      step_size: 1
      refit: false
    val:
      cv_windows: 140   # 10% of 1402 days
      step_size: 1
      refit: false
  ROSSMANN:
    test:
      cv_windows: 188   # 20% of 942 days
      step_size: 1
      refit: false
    val:
      cv_windows: 94    # 10% of 942 days
      step_size: 1
      refit: false
  BAKERY:
    test:
      cv_windows: 243   # 20% of 1215 days
      step_size: 1
      refit: false
    val:
      cv_windows: 121   # 10% of 1215 days
      step_size: 1
      refit: false
  YAZ:
    test:
      cv_windows: 153   # 20% of 765 days
      step_size: 1
      refit: false
    val:
      cv_windows: 76    # 10% of 765 days
      step_size: 1
      refit: false
  PHARMACY:
    test:
      cv_windows: 24   # 20% of 827 days
      step_size: 1
      refit: false
    val:
      cv_windows: 12    # 10% of 827 days
      step_size: 1
      refit: false
  HOTEL:
    test:
      cv_windows: 645   # 20% of 3227 days
      step_size: 1
      refit: false
    val:
      cv_windows: 322   # 10% of 3227 days
      step_size: 1
      refit: false
  ONLINERETAIL:
    test:
      cv_windows: 147   # 20% of 739 days
      step_size: 1
      refit: false
    val:
      cv_windows: 73    # 10% of 739 days
      step_size: 1
      refit: false

metrics:
  metrics:
    - MSSE
    - MASE
  seasonality: null # Set to None for allowing seasonality to be detected automatically based on frequency of the dataset
