log_wandb: false
seed: 42

filepaths:
  eval_results_dir: "data/eval_results/"
  eval_plots_dir: "data/eval_plots/"

input_columns:
  date:    "dateID"
  dp_index:    "bdID"
  sku_index:   "skuID"
  target:  "target"
  frequency: "frequency"

datasets:
  - MAISHAMEDS

forecast_columns:
  date:    "date"
  sku_index:   "skuID"
  target:  "demand"
  cutoff: "cutoff"
  exog_vars:
    - companyID
    - storeID
    - productID
    - not_for_sale
  static:
    - companyID
    - storeID
    - productID

forecast:
  models:
    - LGBM
    - TOTO
    - TABPFN
  horizon: 4
  lags: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  model_config:
    ML:
      num_samples: 50
    FM:
      TOTO:
        num_samples: 50
        samples_per_batch: 25  # Must divide num_samples evenly
      TABPFN:
        n_estimators: 4        # TabPFN ensemble size (internal sampling)
        max_samples: 500       # Max training samples (due to TabPFN limitations)  
        n_lags: 8              # Number of lag features
        scaling: true          # Apply feature scaling

  date_features:
    - month
cross_validation:
  cv_windows: 6
  step_size: 4
  refit: false

metrics:
  metrics:
    - MASE
    - MSSE
    - MSE 
    - MAE
    - RMSE
  seasonality: 52
