log_wandb: false
seed: 42
filepaths:
  processed_data_dir: data/processed/
  sku_stats_dir: data/sku_stats/
  cv_results_dir: data/cv_results/
  eval_results_dir: data/eval_results/
  eval_plots_dir: data/eval_plots/
  file_format: CSV
input_columns:
  date: dateID
  dp_index: bdID
  sku_index: skuID
  target: target
  frequency: frequency
datasets:
- BAKERY
forecast_columns:
  date: date
  sku_index: skuID
  product_index: productID
  store_index: storeID
  target: demand
  cutoff: cutoff
preprocessing:
  target_transform: LOCAL_MAX
forecast:
  models:
  - TIDE
  model_config:
    ML:
      num_samples: 1
    FM:
      TOTO:
        num_samples: 50
        samples_per_batch: 25
      TABPFN:
        n_estimators: 4
        max_samples: 500
        scaling: true
    NEURAL:
      gpus: 1
      cpus: 1
      num_samples: 1
      quantile:
        min: 1
        max: 99
        step: 1
cross_validation:
  M5:
    test:
      n_windows: 322
      step_size: 1
      refit: false
    val:
      n_windows: 100
      step_size: 1
      refit: false
  FAVORITA:
    test:
      n_windows: 322
      step_size: 1
      refit: false
    val:
      n_windows: 100
      step_size: 1
      refit: false
  ROHLIK:
    test:
      n_windows: 280
      step_size: 1
      refit: false
    val:
      n_windows: 140
      step_size: 1
      refit: false
  ROSSMANN:
    test:
      n_windows: 188
      step_size: 1
      refit: false
    val:
      n_windows: 94
      step_size: 1
      refit: false
  BAKERY:
    test:
      n_windows: 243
      step_size: 1
      refit: false
    val:
      n_windows: 121
      step_size: 1
      refit: false
  YAZ:
    test:
      n_windows: 153
      step_size: 1
      refit: false
    val:
      n_windows: 76
      step_size: 1
      refit: false
  PHARMACY:
    test:
      n_windows: 24
      step_size: 1
      refit: false
    val:
      n_windows: 12
      step_size: 1
      refit: false
  HOTEL:
    test:
      n_windows: 645
      step_size: 1
      refit: false
    val:
      n_windows: 322
      step_size: 1
      refit: false
  ONLINERETAIL:
    test:
      n_windows: 147
      step_size: 1
      refit: false
    val:
      n_windows: 73
      step_size: 1
      refit: false
metrics:
  metrics:
  - MASE
  - SCALED_MQLOSS
  seasonality: null
  quantiles:
    min: 1
    max: 99
    step: 1
lags:
  PHARMACY:
    daily: 50
    weekly: 15
  M5:
    daily: 50
    weekly: 15
  FAVORITA:
    daily: 50
    weekly: 15
  ROHLIK:
    daily: 50
    weekly: 15
  ROSSMANN:
    daily: 50
    weekly: 15
  BAKERY:
    daily: 50
    weekly: 15
  YAZ:
    daily: 50
    weekly: 15
  HOTEL:
    daily: 50
    weekly: 15
  ONLINERETAIL:
    daily: 50
    weekly: 15
