log_wandb: false
seed: 42

filepaths:
  eval_results_dir: "data/eval_result/"
  eval_plots_dir: "data/eval_plots/"

input_columns:
  date:    "dateID"
  dp_index:    "bdID"
  sku_index:   "skuID"
  target:  "target"

datasets:
  - M5
  - FAVORITA
  - BAKERY

forecast_columns:
  date:    "date"
  sku_index:   "skuID"
  target:  "demand"
  cutoff: "cutoff"
  exog_vars:
    - companyID
    - storeID
    - productID
    - not_for_sale
  static:
    - companyID
    - storeID
    - productID

forecast:
  models:
    - CES
    - ETS
  freq: "D"
  season_length: 7
  horizon: 14
  lags: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
  date_features:
    - dayofweek
    - month
cross_validation:
  cv_windows: 6
  step_size: 14
  refit: false

metrics:
  metrics:
    - MASE
    - MSSE
  seasonality: 7
